# Generated by Django 5.2 on 2025-05-09 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="breach_details",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterUniqueTogether(
            name="credential",
            unique_together={("user", "email")},
        ),
    ]
